name: Periodic health check pipeline

on:
  schedule:
    - cron: "30 * * * *"

jobs:
  check_health:
    runs-on: ubuntu-20.04
    steps:
      - uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-7vgh.onrender.com
          max-attempts: 3
          retry-delay: 5s
